openapi: 3.0.0
info:
  title: Miro-like Collaborative Whiteboard API
  description: API for a collaborative whiteboard application similar to Miro
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/login:
    post:
      $ref: './endpoints/auth.yaml#/login'

  /auth/register:
    post:
      $ref: './endpoints/auth.yaml#/register'

  /auth/refresh:
    post:
      $ref: './endpoints/auth.yaml#/refresh'

  /cards:
    get:
      $ref: './endpoints/cards.yaml#/getAllCards'

    post:
      $ref: './endpoints/cards.yaml#/createCard'

  /cards/{cardId}:
    delete:
      $ref: './endpoints/cards.yaml#/deleteCard'
