// import createFetchClient from 'openapi-fetch'
// import createClient from 'openapi-react-query'
// // import type { paths } from './schema/generated' // generated by openapi-typescript
// import { CONFIG } from '../model/config'
// import type { ApiPaths } from './schema'

// export const fetchClient = createFetchClient<ApiPaths>({
//   baseUrl: CONFIG.API_BASE_URL
// })

// export const rqClient = createClient(fetchClient)

import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
import { CONFIG } from '../model/config'
import type { ApiPaths, ApiSchemas } from './schema'
import { useSession } from '../model/session'

export const publicFetchClient = createFetchClient<ApiPaths>({
  baseUrl: CONFIG.API_BASE_URL
})
export const publicRqClient = createClient(publicFetchClient)

// =================================================

export const privateFetchClient = createFetchClient<ApiPaths>({
  baseUrl: CONFIG.API_BASE_URL
})

export const privateRqClient = createClient(privateFetchClient)

privateFetchClient.use({
  async onRequest({ request }) {
    const token = await useSession.getState().refreshToken()

    if (token) {
      request.headers.set('Authorization', `Bearer ${token}`)
    } else {
      console.error({
        code: 'NOT_AUTHORIZED',
        message: 'У вас нет прав доступа к этому ресурсу'
      })

      return new Response(
        JSON.stringify({
          code: 'NOT_AUTHORIZED',
          message: 'У вас нет прав доступа к этому ресурсу'
        } as ApiSchemas['Error']),
        {
          status: 401,
          headers: {
            'Content-Type': 'application/json'
          }
        }
      )
    }
  }
})
